### ISSUE TITLE
Wrong currency for locale

### ISSUE THREAD

**Issue by blaired** [Tanddant/ROI-Calculator#1]
Hi there :-),

Great bit of code.  I'm looking at using this but I am having an issue with the currency, it defaults to USD and not GBP.  For the record I'm not a React person but when I do look at the code in Visual I see references to locale, does it think I'm US based and not UK.  Is there a way to hard code to just GBP?

**Comment by Tanddant** [comment]
Hi @blaired - It does indeed default to USD, I haven't actually attempted to get the default currency for the users current locale, the default values are honestly a bit of a mismatch of random things, I think the currency is US, working hours and days are based of Denmark, and Salary I dont even remember 😅

You can however add a query parameter to change it: 

`?Currency=GBP`

Any value you can change in the solution will be pushed to a query parameter, so you can enter the values that're relevant to you, and then share that full link with the stakeholders 😊

I hope that clears it up a bit

**Comment by blaired** [comment]
Perfect, thank you all working.

PS Congrats on the MVP

**Comment by Tanddant** [comment]
You're very welcome, feel free to implement an override for the default behavior, would be pretty neat 🤔

Thank you 😊
